arb-dir: lib/l10n
template-arb-file: app_en.arb
nullable-getter: false

output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/l10n/generated
untranslated-messages-file: lib/l10n/generated/untranslated_report.txt
