name: q_slope_calculator
description: "An application which calculates Q-slope of a rock expressing the quality of the rock mass for slope stability."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  collection: ^1.18.0
  flutter_bloc: ^8.1.6
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  husky: ^0.1.7
  lint_staged: ^0.5.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/illustrations/
    - assets/images/
    - .env

lint_staged:
  "lib/**.dart": dart format --fix && dart fix --apply
