name: q_slope_calculator
description: "An application which calculates Q-slope of a rock expressing the quality of the rock mass for slope stability."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  collection: ^1.18.0
  flutter_bloc: ^8.1.6
  logger: ^2.4.0
  photo_view: ^0.15.0
  toastification: ^2.1.0
  package_info_plus: ^8.0.1
  url_launcher: ^6.3.0
  responsive_framework: ^1.4.0
  uuid: ^4.4.2
  syncfusion_flutter_xlsio: ^26.2.10
  file_picker: ^8.1.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  husky: ^0.1.7
  lint_staged: ^0.5.1
  msix: ^3.16.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/illustrations/
    - assets/images/
    - .env

msix_config:
  display_name: Q-slope Calculator
  publisher_display_name: Saarthak Gupta
  identity_name: in.sg.qslopecalculator
  msix_version: 1.0.0.0
  logo_path: assets/images/icon.png

lint_staged:
  "lib/**.dart": dart format --fix && dart fix --apply
