name: Build & Deploy Web

on:
  push:
    branches:
      - master

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.event.inputs.tag_version }}

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env file
        env:
          RELEASE_ENV: ${{ secrets.RELEASE_ENV }}
        run: echo -n "${RELEASE_ENV}" > .env 
      
      - run: flutter analyze -v

      - name: Build Flutter Web
        run: flutter build web --release --base-href="/q-slope-calculator/"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: web-build
          path: build/web/
          include-hidden-files: true

  deploy-web:
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: web-build
          path: build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
