name: Build Windows

on:
  workflow_dispatch: # Manual trigger
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5.6.0
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: subosito/flutter-action@v2.23.0
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64
          flutter-version-file: pubspec.yaml

      - name: Print flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze -v

      - name: Test code
        run: flutter test

  #       - name: Upload build files as artifact
  #         uses: actions/upload-artifact@7
  #         with:
  #           name: q-slope-calculator-windows
  #           path: |
  #             build/windows/x64/runner/Release
  #           overwrite: true
  #           include-hidden-files: true
