name: Build & Deploy Android

on:
  push:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64

      - name: Print flutter version
        run: flutter --version

      - name: Create .env file
        run: echo -n "${RELEASE_ENV}" > .env

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze -v

      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed .

      - name: Create release key and release key properties from secrets
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PROPERTIES: ${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}
        run: |
          echo -n "${RELEASE_KEYSTORE}" | base64 -d > android/keys/release.keystore
          echo "${RELEASE_KEYSTORE_PROPERTIES}" > android/keys/release-key.properties

      - name: Run build
        run: flutter build appbundle --release --flavor prod

      - name: Zip merged_native_libs
        run: |
          cd build/app/intermediates/merged_native_libs/prodRelease/out/lib
          zip -r merged_native_libs.zip .

      - name: Upload build files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod-release
          path: |
            build/app/outputs/bundle/prodRelease/app-prod-release.aab
            build/app/outputs/mapping/prodRelease/mapping.txt
            build/app/intermediates/merged_native_libs/prodRelease/out/lib/merged_native_libs.zip
          overwrite: true

  deploy-playstore:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: prod-release
          path: artifact

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: in.sg.q_slope_calculator
          releaseFiles: artifact/outputs/bundle/prodRelease/app-prod-release.aab
          track: internal
          mappingFile: artifact/outputs/mapping/prodRelease/mapping.txt
          debugSymbols: artifact/intermediates/merged_native_libs/prodRelease/out/lib/merged_native_libs.zip
