name: Create Tag and Release

on:
  push:
    branches:
      - master 

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | sed 's/version: //; s/+.*//')
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create tag
        run: |
          git tag ${{ steps.version.outputs.VERSION }}
          git push origin ${{ steps.version.outputs.VERSION }}

      - name: Create GitHub release
        run: |
          gh release create ${{ steps.version.outputs.VERSION }} \
            --title "Release ${{ steps.version.outputs.VERSION }}" \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
